# -*- encoding: utf-8 -*-

=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

$:.push File.expand_path("../lib", __FILE__)
require "yousign_client/version"

Gem::Specification.new do |s|
  s.name        = "yousign_client"
  s.version     = YousignClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Thomas Burgaud"]
  s.email       = ["thomas.burgaud@cashbee.fr"]
  s.homepage    = "https://github.com/cashbee-team/yousign_client"
  s.summary     = "Yousign API Documentation Ruby Gem"
  s.description = "Yousign API Documentation Ruby Gem"
  s.license     = 'Apache-2.0'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'irb'
  s.add_development_dependency 'json'
  s.add_development_dependency 'net-http'
  s.add_development_dependency 'uri'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
