=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::ConsumptionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConsumptionApi' do
  before do
    # run before each test
    @instance = YousignClient::ConsumptionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConsumptionApi' do
    it 'should create an instance of ConsumptionApi' do
      expect(@instance).to be_instance_of(YousignClient::ConsumptionApi)
    end
  end

  # unit tests for get_consumptions
  # Get consumptions
  # Get signatures consumption by source.
  # @param from \&quot;from\&quot; date must be inferior or equal to \&quot;to\&quot;
  # @param to 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authentication_key 
  # @return [InlineResponse2004]
  describe 'get_consumptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_consumptions_export
  # Export consumption data
  # Get a binary .csv file containing all the underlying data of signatures consumption.
  # @param from \&quot;from\&quot; date must be inferior or equal to \&quot;to\&quot;
  # @param to 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authentication_key 
  # @return [String]
  describe 'get_consumptions_export test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
