=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::ContactApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactApi' do
  before do
    # run before each test
    @instance = YousignClient::ContactApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactApi' do
    it 'should create an instance of ContactApi' do
      expect(@instance).to be_instance_of(YousignClient::ContactApi)
    end
  end

  # unit tests for delete_contacts_contact_id
  # Delete a contact
  # Delete a contact
  # @param contact_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_contacts_contact_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_contact_contact_id
  # Get a contact
  # Get a contact
  # @param contact_id 
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'get_contact_contact_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_contacts
  # List all contacts
  # List all contacts
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @return [InlineResponse2002]
  describe 'get_contacts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_contacts
  # Create a contact
  # Create a contact
  # @param [Hash] opts the optional parameters
  # @option opts [ContactsBody] :body 
  # @return [Contact]
  describe 'post_contacts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
