=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::CustomExperienceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomExperienceApi' do
  before do
    # run before each test
    @instance = YousignClient::CustomExperienceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomExperienceApi' do
    it 'should create an instance of CustomExperienceApi' do
      expect(@instance).to be_instance_of(YousignClient::CustomExperienceApi)
    end
  end

  # unit tests for delete_custom_experience
  # Delete a Custom Experience
  # Delete a Custom Experience
  # @param custom_experience_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_custom_experience test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_custom_experience_logo
  # Delete a Custom Experience Logo
  # Delete a Custom Experience Logo
  # @param custom_experience_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_custom_experience_logo test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_custom_experiences
  # List Custom Experiences
  # List Custom Experiences
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @return [InlineResponse2005]
  describe 'get_custom_experiences test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_custom_experiences_custom_experience_id
  # Get a given Custom Experience
  # Get a given Custom Experience
  # @param custom_experience_id 
  # @param [Hash] opts the optional parameters
  # @return [Paths1customExperiencespostresponses201contentapplication1jsonschema]
  describe 'get_custom_experiences_custom_experience_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_custom_experience_logo
  # Update a Custom Experience Logo
  # Create a Custom Experience Logo
  # @param custom_experience_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @return [Paths1customExperiencespostresponses201contentapplication1jsonschema]
  describe 'patch_custom_experience_logo test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_custom_experiences_custom_experience_id
  # Update a Custom Experience
  # Update a Custom Experience
  # @param custom_experience_id 
  # @param [Hash] opts the optional parameters
  # @option opts [CustomExperienceInput] :body 
  # @return [Paths1customExperiencespostresponses201contentapplication1jsonschema]
  describe 'patch_custom_experiences_custom_experience_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_custom_experience
  # Create a Custom Experience
  # Create a Custom Experience
  # @param [Hash] opts the optional parameters
  # @option opts [CustomExperienceInput] :body 
  # @return [CustomExperience]
  describe 'post_custom_experience test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
