=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::DocumentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DocumentApi' do
  before do
    # run before each test
    @instance = YousignClient::DocumentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentApi' do
    it 'should create an instance of DocumentApi' do
      expect(@instance).to be_instance_of(YousignClient::DocumentApi)
    end
  end

  # unit tests for delete_signature_requests_signature_request_id_documents_document_id
  # Delete a document
  # Delete a document
  # @param signature_request_id Signature request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_signature_requests_signature_request_id_documents_document_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents
  # List signature request documents
  # List signature request documents
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :nature filter by nature
  # @return [Array<Document>]
  describe 'get_signature_requests_signature_request_id_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents_document_id
  # Get a document
  # Get a document
  # @param signature_request_id Signature request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @return [Document]
  describe 'get_signature_requests_signature_request_id_documents_document_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents_documents_id_download
  # Download a single Signature Request Document
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_signature_requests_signature_request_id_documents_documents_id_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents_download
  # Download signature request documents
  # Download signature request documents
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :version Specify documents version to download, \&quot;completed\&quot; is only available when the signature request status is \&quot;done\&quot;.
  # @option opts [BOOLEAN] :archive Force zip archive download
  # @return [String]
  describe 'get_signature_requests_signature_request_id_documents_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_signature_requests_signature_request_id_documents_document_id
  # Update a document
  # Update a document
  # @param signature_request_id Signature request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @option opts [DocumentsDocumentIdBody] :body 
  # @return [Document]
  describe 'patch_signature_requests_signature_request_id_documents_document_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_documents
  # Upload a document
  # Upload a document
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :nature 
  # @option opts [String] :password 
  # @option opts [BOOLEAN] :parse_anchors 
  # @option opts [InitialsArea] :initials 
  # @return [Document]
  describe 'post_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_documents
  # Add document to a signature request
  # Add document to a signature request
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :nature 
  # @option opts [String] :password 
  # @option opts [] :initials 
  # @option opts [BOOLEAN] :parse_anchors 
  # @return [Document]
  describe 'post_signature_requests_signature_request_id_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_documents_document_id_replace
  # Replace a document
  # Replace a document in a signature request
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @return [Document]
  describe 'post_signature_requests_signature_request_id_documents_document_id_replace test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
