=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::ElectronicSealApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ElectronicSealApi' do
  before do
    # run before each test
    @instance = YousignClient::ElectronicSealApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ElectronicSealApi' do
    it 'should create an instance of ElectronicSealApi' do
      expect(@instance).to be_instance_of(YousignClient::ElectronicSealApi)
    end
  end

  # unit tests for download_electronic_seal_audit_trail
  # Download electronic seal audit trail
  # Download electronic seal audit trail
  # @param electronic_seal_id 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_electronic_seal_audit_trail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for download_electronic_seal_document
  # Download electronic seal document
  # Download electronic seal document
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_electronic_seal_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_electronic_seal
  # Get electronic seal
  # Get an electronic seal
  # @param electronic_seal_id 
  # @param [Hash] opts the optional parameters
  # @return [Paths1electronicSealspostresponses201contentapplication1jsonschema]
  describe 'get_electronic_seal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_electronic_seal_audit_trail
  # Get electronic seal audit trail
  # Get electronic seal audit trail
  # @param electronic_seal_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2006]
  describe 'get_electronic_seal_audit_trail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_electronic_seals
  # Create Electronic Seal
  # Create an electronic seal
  # @param [Hash] opts the optional parameters
  # @option opts [CreateElectronicSealPayload] :body 
  # @return [ElectronicSeal]
  describe 'post_electronic_seals test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_electronic_seal_document
  # Upload electronic seal document
  # Upload electronic seal document
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :password 
  # @return [InlineResponse2011]
  describe 'upload_electronic_seal_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_electronic_seal_image
  # Upload electronic seal image
  # Upload electronic seal image
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :name 
  # @return [InlineResponse201]
  describe 'upload_electronic_seal_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
