=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::SignatureRequestApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SignatureRequestApi' do
  before do
    # run before each test
    @instance = YousignClient::SignatureRequestApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SignatureRequestApi' do
    it 'should create an instance of SignatureRequestApi' do
      expect(@instance).to be_instance_of(YousignClient::SignatureRequestApi)
    end
  end

  # unit tests for delete_signature_requests_signature_request_id
  # Delete a signature request
  # Delete a signature request (in draft status)
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_signature_requests_signature_request_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests
  # List signature requests
  # List signature requests
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Filter by status
  # @option opts [String] :after After cursor (pagination)
  # @option opts [String] :external_id Filter by external_id
  # @option opts [Array<String>] :source Filter by source
  # @return [InlineResponse200]
  describe 'get_signature_requests test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id
  # Fetch a signature request
  # Fetch a signature request
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @return [SignatureRequest]
  describe 'get_signature_requests_signature_request_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_audit_trails_download
  # Download signature request audit trails
  # Download signature request audit trails
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_signature_requests_signature_request_id_audit_trails_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_signature_requests_signature_request_id
  # Update a Signature Request
  # Update a Signature Request
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [SignatureRequestsSignatureRequestIdBody] :body 
  # @return [SignatureRequest]
  describe 'patch_signature_requests_signature_request_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests
  # Initiate a new signature request
  # Initiate a new signature request
  # @param [Hash] opts the optional parameters
  # @option opts [SignatureRequestsBody] :body 
  # @return [SignatureRequest]
  describe 'post_signature_requests test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_cancel
  # Cancel a signature request
  # Cancel a signature request
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [SignatureRequestIdCancelBody] :body 
  # @return [SignatureRequest]
  describe 'post_signature_requests_signature_request_id_cancel test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_reactivate
  # Reactivate an expired signature request
  # Reactivate a signature request
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [SignatureRequestIdReactivateBody] :body 
  # @return [SignatureRequest]
  describe 'post_signature_requests_signature_request_id_reactivate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_signatures
  # Activate a signature request
  # Activate a signature request
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @return [SignatureRequestActivated]
  describe 'post_signature_requests_signature_request_id_signatures test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_signers_signer_id_send_reminder
  # Send manual reminder to signer
  # Send manual reminder to signer
  # @param signer_id Signer id
  # @param signature_request_id Signature request id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_signature_requests_signature_request_id_signers_signer_id_send_reminder test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
