=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::WebhookApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhookApi' do
  before do
    # run before each test
    @instance = YousignClient::WebhookApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookApi' do
    it 'should create an instance of WebhookApi' do
      expect(@instance).to be_instance_of(YousignClient::WebhookApi)
    end
  end

  # unit tests for delete_webhooks_webhook_id
  # Unsubscribe a webhook
  # Unsubscribe a webhook
  # @param webhook_id Webhook Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_webhooks_webhook_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhooks
  # List webhooks
  # List webhooks
  # @param [Hash] opts the optional parameters
  # @return [Array<WebhookSubscription>]
  describe 'get_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhooks_webhook_id
  # Get a webhook
  # Get a webhook
  # @param webhook_id Webhook Id
  # @param [Hash] opts the optional parameters
  # @return [WebhookSubscription]
  describe 'get_webhooks_webhook_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_webhooks_webhook_id
  # Update a webhook
  # Update a webhook
  # @param webhook_id Webhook Id
  # @param [Hash] opts the optional parameters
  # @option opts [WebhooksWebhookIdBody] :body 
  # @return [WebhookSubscription]
  describe 'patch_webhooks_webhook_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_webhooks_subscriptions
  # Configure a new webhook
  # Configure a new webhook
  # @param [Hash] opts the optional parameters
  # @option opts [WebhooksBody] :body 
  # @return [WebhookSubscription]
  describe 'post_webhooks_subscriptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
