=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClient::WorkspaceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WorkspaceApi' do
  before do
    # run before each test
    @instance = YousignClient::WorkspaceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkspaceApi' do
    it 'should create an instance of WorkspaceApi' do
      expect(@instance).to be_instance_of(YousignClient::WorkspaceApi)
    end
  end

  # unit tests for get_workspaces
  # List workspaces
  # List workspaces
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @return [InlineResponse2007]
  describe 'get_workspaces test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
