=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.42
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for YousignClient::OneOfwebhooksBodyScopes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OneOfwebhooksBodyScopes' do
  before do
    # run before each test
    @instance = YousignClient::OneOfwebhooksBodyScopes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OneOfwebhooksBodyScopes' do
    it 'should create an instance of OneOfwebhooksBodyScopes' do
      expect(@instance).to be_instance_of(YousignClient::OneOfwebhooksBodyScopes)
    end
  end
end
