=begin
#Yousign API Swagger

#For your information, the Yousign API documentation is available at https://dev.yousign.com/

OpenAPI spec version: 2.1
Contact: support@yousign.fr
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'

describe YousignClient::Configuration do
  let(:config) { YousignClient::Configuration.default }

  before(:each) do
    require 'URI'
    uri = URI.parse("https://api.yousign.com")
    YousignClient.configure do |c|
      c.host = uri.host
      c.base_path = uri.path
    end
  end

  describe '#base_url' do
    it 'should have the default value' do
      expect(config.base_url).to eq("https://api.yousign.com")
    end

    it 'should remove trailing slashes' do
      [nil, '', '/', '//'].each do |base_path|
        config.base_path = base_path
        expect(config.base_url).to eq("https://api.yousign.com")
      end
    end
  end
end
